### ISSUE TITLE
Update the Data Please

### ISSUE THREAD

**Issue by laurenponsonby** [HanjoStudy/sarbR#9]
Hi, I hope you are well.

Your Library is exceptionally useful for the work I am doing, however the last the time the data was updated is "2021-12-15"

Is it possible to have the data updated?

Thanks,
Lauren

**Comment by HanjoStudy** [comment]
Hi Lauren, 

Thank you for reaching out. I had a quick look and there was a small bug in how the function `sarbR::release_info()` returns the latest date. This has been fixed. 

That said, the data on the server is still the latest available information.

``` r
library(sarbR)
sarbR::release_info()
#> [1] "2022-12-15"

sarb_code(code = "KBP1008M") %>% 
  tail
#> # A tibble: 6 × 6
#>   date       original_date classification             frequency code      value
#>   <chr>      <chr>         <chr>                      <chr>     <chr>     <int>
#> 1 2022-06-01 20220600      01_kbp_1_money_and_banking M1        KBP1008M 385001
#> 2 2022-07-01 20220700      01_kbp_1_money_and_banking M1        KBP1008M 375753
#> 3 2022-08-01 20220800      01_kbp_1_money_and_banking M1        KBP1008M 385292
#> 4 2022-09-01 20220900      01_kbp_1_money_and_banking M1        KBP1008M 385746
#> 5 2022-10-01 20221000      01_kbp_1_money_and_banking M1        KBP1008M 390381
#> 6 2022-11-01 20221100      01_kbp_1_money_and_banking M1        KBP1008M     NA
```

<sup>Created on 2023-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
